### ISSUE TITLE
"ReturnFields" and "ReturnFields+" breaks codegen for Go

### ISSUE THREAD

**Issue by jimrazmus** [infobloxopen/infoblox-swagger-wapi#4]
ReturnFields and ReturnFields+ in the JSON files results in broken Go code due to attempts to redeclare 'ReturnFields'. I suspect the OpenAPI specification is incorrect. You can see the code generated using deepmap/oapi-codegen here: github.com/jimrazmus/infoblox-client

**Comment by DerPhlipsi** [comment]
Hey @jimrazmus,

this is not an issue with the OpenAPI specification made by Infoblox (well, maybe a tiny bit, but oh well) but more of a detail of how code generation is done using the specification.

Almost every Infoblox WAPI call can have the parameters  "_return_fields" and "_return_fields+". The problem is that most (if not all) code generators that convert an OAS to code will simply strip the + from "_return_fields+", which results in a duplication of a parameter name. This is an implementation detail of the used code generator, not a incorrect specification. Yes, you could argue that using a + with "_return_fields+" is technically a bad choice, but in some way it also makes sense logically (since I want the default fields PLUS my list of fields).

My solution at the moment for this, until I found an official way around it or patched swagger-codegen/openapi-codegen:

1. Renamed every occurrence of "_return_fields+" in the spec to "_return_fieldsPlus"
2. generate code (Java in my case)
3. have a maven plugin go through the generated code and replace every "_return_fieldsPlus" with "_return_fields+".

This way, the parameter itself is named _return_fieldsPlus (not really nice or to any Java code standard, meh, but it works) and any reference to the name to be used for URL generation etc. is "_return_fields+".


Hope I could help.
Greetings,
Phil

**Comment by jimrazmus** [comment]
I appreciate you taking the time to follow up. I was looking for a very low effort way to ultimately modernize the Terraform provider for InfoBlox. This is turning into a larger project than I have time for however. Feel free to close this issue.

Best regards,
Jim
